-- ============================================================
-- AI PROCESS VIP V2 upgrade
-- - 75 avatar keys
-- - AI PROCESS sessions / logs
-- - public live progress list
-- - admin start / stop
-- - member 5-minute market tick synchronization
-- Run once in Supabase SQL Editor after 01_current_schema.sql.
-- ============================================================

begin;

create extension if not exists pgcrypto;

create table if not exists public.ai_process_sessions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  status text not null default 'idle' check (status in ('idle','running','completed','stopped')),
  start_amount numeric(18,2) not null default 0,
  current_amount numeric(18,2) not null default 0,
  total_profit numeric(18,2) not null default 0,
  total_return numeric(12,6) not null default 0,
  duration_hours integer not null default 24 check (duration_hours between 1 and 720),
  started_at timestamptz,
  ends_at timestamptz,
  completed_at timestamptz,
  last_market_at timestamptz,
  last_asset_symbol text,
  last_asset_name text,
  last_asset_type text,
  last_market_pct numeric(12,6),
  last_delta numeric(18,2),
  updated_at timestamptz not null default now()
);

create index if not exists ai_process_sessions_status_idx
  on public.ai_process_sessions(status, updated_at desc);

create table if not exists public.ai_process_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  market_at timestamptz not null,
  asset_symbol text,
  asset_name text,
  asset_type text,
  market_pct numeric(12,6) not null default 0,
  amount_before numeric(18,2) not null default 0,
  delta numeric(18,2) not null default 0,
  amount_after numeric(18,2) not null default 0,
  result_type text not null check (result_type in ('profit','loss','wait')),
  created_at timestamptz not null default now(),
  unique(user_id, market_at)
);

create index if not exists ai_process_logs_user_market_idx
  on public.ai_process_logs(user_id, market_at desc);

alter table public.ai_process_sessions enable row level security;
alter table public.ai_process_logs enable row level security;

-- Approved members can read live session summaries. Writes happen through RPC only.
drop policy if exists "approved members can read ai process sessions" on public.ai_process_sessions;
create policy "approved members can read ai process sessions"
on public.ai_process_sessions for select
to authenticated
using (
  exists (
    select 1 from public.profiles me
    where me.id = auth.uid()
      and me.approval_status = 'approved'
  )
);

-- Detailed logs are private to the member and admins.
drop policy if exists "member or admin can read ai process logs" on public.ai_process_logs;
create policy "member or admin can read ai process logs"
on public.ai_process_logs for select
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.profiles me
    where me.id = auth.uid()
      and me.role = 'admin'
      and me.approval_status = 'approved'
  )
);

grant select on public.ai_process_sessions to authenticated;
grant select on public.ai_process_logs to authenticated;

-- 24 compact profiles + six legacy keys.
create or replace function public.set_my_avatar(new_avatar text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if new_avatar !~ '^(vip_0[1-6]|(dog|cat|redpanda|quokka|penguin|panda|hedgehog|squirrel|meerkat|beaver|rabbit|otter)-(gold|blue|black))$' then
    raise exception 'Invalid avatar';
  end if;

  update public.profiles
  set avatar = new_avatar
  where id = auth.uid()
    and approval_status = 'approved';

  if not found then
    raise exception 'Approved profile not found';
  end if;
end;
$$;

grant execute on function public.set_my_avatar(text) to authenticated;

-- Public live list. It exposes only the fields intended for the shared AI PROCESS panel.
create or replace function public.get_ai_process_public_sessions()
returns table(
  user_id uuid,
  nickname text,
  avatar text,
  status text,
  start_amount numeric,
  current_amount numeric,
  total_profit numeric,
  total_return numeric,
  duration_hours integer,
  started_at timestamptz,
  ends_at timestamptz,
  last_asset_symbol text,
  last_asset_name text,
  last_asset_type text,
  last_market_pct numeric,
  last_delta numeric,
  updated_at timestamptz
)
language sql
security definer
set search_path to 'public'
as $$
  select
    s.user_id,
    p.nickname,
    p.avatar,
    s.status,
    s.start_amount,
    s.current_amount,
    s.total_profit,
    s.total_return,
    s.duration_hours,
    s.started_at,
    s.ends_at,
    s.last_asset_symbol,
    s.last_asset_name,
    s.last_asset_type,
    s.last_market_pct,
    s.last_delta,
    s.updated_at
  from public.ai_process_sessions s
  join public.profiles p on p.id = s.user_id
  where s.status = 'running'
    and p.approval_status = 'approved'
    and exists (
      select 1 from public.profiles me
      where me.id = auth.uid()
        and me.approval_status = 'approved'
    )
  order by s.updated_at desc, p.nickname asc;
$$;

grant execute on function public.get_ai_process_public_sessions() to authenticated;

create or replace function public.admin_start_ai_process(
  target_user_id uuid,
  starting_amount numeric,
  process_duration_hours integer
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not exists (
    select 1 from public.profiles me
    where me.id = auth.uid()
      and me.role = 'admin'
      and me.approval_status = 'approved'
  ) then
    raise exception '관리자만 AI PROCESS를 시작할 수 있습니다.';
  end if;

  if starting_amount is null or starting_amount <= 0 then
    raise exception '운용금액은 0보다 커야 합니다.';
  end if;

  if process_duration_hours is null or process_duration_hours < 1 or process_duration_hours > 720 then
    raise exception '진행시간은 1시간~720시간이어야 합니다.';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = target_user_id
      and p.approval_status = 'approved'
      and coalesce(p.role,'member') <> 'admin'
  ) then
    raise exception '승인된 회원을 찾을 수 없습니다.';
  end if;

  insert into public.ai_process_sessions(
    user_id,status,start_amount,current_amount,total_profit,total_return,duration_hours,
    started_at,ends_at,completed_at,last_market_at,last_asset_symbol,last_asset_name,
    last_asset_type,last_market_pct,last_delta,updated_at
  ) values (
    target_user_id,'running',starting_amount,starting_amount,0,0,process_duration_hours,
    now(),now() + make_interval(hours => process_duration_hours),null,null,null,null,null,null,null,now()
  )
  on conflict(user_id) do update set
    status='running',
    start_amount=excluded.start_amount,
    current_amount=excluded.current_amount,
    total_profit=0,
    total_return=0,
    duration_hours=excluded.duration_hours,
    started_at=excluded.started_at,
    ends_at=excluded.ends_at,
    completed_at=null,
    last_market_at=null,
    last_asset_symbol=null,
    last_asset_name=null,
    last_asset_type=null,
    last_market_pct=null,
    last_delta=null,
    updated_at=now();

  delete from public.ai_process_logs where user_id = target_user_id;
end;
$$;

grant execute on function public.admin_start_ai_process(uuid,numeric,integer) to authenticated;

create or replace function public.admin_stop_ai_process(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not exists (
    select 1 from public.profiles me
    where me.id = auth.uid()
      and me.role = 'admin'
      and me.approval_status = 'approved'
  ) then
    raise exception '관리자만 AI PROCESS를 종료할 수 있습니다.';
  end if;

  update public.ai_process_sessions
  set status='stopped', completed_at=now(), updated_at=now()
  where user_id = target_user_id and status='running';
end;
$$;

grant execute on function public.admin_stop_ai_process(uuid) to authenticated;

-- One 5-minute result for the current signed-in member.
-- The server calculates delta from the stored current amount and the linked market percentage.
create or replace function public.record_ai_process_tick(
  market_at timestamptz,
  asset_symbol text,
  asset_name text,
  asset_type text,
  market_pct numeric
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  s public.ai_process_sessions%rowtype;
  v_before numeric;
  v_delta numeric;
  v_after numeric;
  v_result text;
begin
  select * into s
  from public.ai_process_sessions
  where user_id = auth.uid()
  for update;

  if not found or s.status <> 'running' then
    raise exception '진행 중인 AI PROCESS가 없습니다.';
  end if;

  if s.ends_at is not null and now() >= s.ends_at then
    update public.ai_process_sessions
    set status='completed', completed_at=now(), updated_at=now()
    where user_id=auth.uid();
    raise exception 'AI PROCESS 진행시간이 종료되었습니다.';
  end if;

  if s.last_market_at is not null and market_at <= s.last_market_at then
    return to_jsonb(s);
  end if;

  v_before := s.current_amount;
  v_delta := round(v_before * coalesce(market_pct,0) / 100.0, 2);
  v_after := greatest(0, v_before + v_delta);
  v_result := case when v_delta > 0 then 'profit' when v_delta < 0 then 'loss' else 'wait' end;

  update public.ai_process_sessions
  set current_amount=v_after,
      total_profit=v_after-start_amount,
      total_return=case when start_amount > 0 then ((v_after-start_amount)/start_amount)*100 else 0 end,
      last_market_at=market_at,
      last_asset_symbol=asset_symbol,
      last_asset_name=asset_name,
      last_asset_type=asset_type,
      last_market_pct=coalesce(market_pct,0),
      last_delta=v_delta,
      updated_at=now()
  where user_id=auth.uid()
  returning * into s;

  insert into public.ai_process_logs(
    user_id,market_at,asset_symbol,asset_name,asset_type,market_pct,
    amount_before,delta,amount_after,result_type
  ) values (
    auth.uid(),market_at,asset_symbol,asset_name,asset_type,coalesce(market_pct,0),
    v_before,v_delta,v_after,v_result
  )
  on conflict(user_id,market_at) do nothing;

  return to_jsonb(s);
end;
$$;

grant execute on function public.record_ai_process_tick(timestamptz,text,text,text,numeric) to authenticated;

-- Add session summary table to Realtime once.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='ai_process_sessions'
  ) then
    alter publication supabase_realtime add table public.ai_process_sessions;
  end if;
end $$;

commit;
