-- ============================================================
-- AI PROCESS V17.5 - DUAL AI PROVIDER + STABILITY CORE
-- 2026-10-06
--
-- 목적
-- 1) Gemini 의존 제거 후 Cloudflare Workers AI / Groq 이중 공급자 운용
-- 2) 공급자 오류를 정확히 기록하고 401/403/429/5xx에 따라 일시 중지
-- 3) 두 공급자 모두 실패했을 때 1분마다 무한 재호출하지 않음
-- 4) 멈춘 processing 큐를 자동 복구할 수 있도록 상태 기반 정비
--
-- 이 SQL은 기존 회원/메시지/프로세스/관계/기억 데이터를 삭제하지 않습니다.
-- ============================================================

begin;

create table if not exists public.ai_provider_health (
  provider text primary key check (provider in ('cloudflare','groq')),
  status text not null default 'unknown'
    check (status in ('unknown','healthy','paused','blocked')),
  paused_until timestamptz,
  last_error_code text,
  last_error_message text,
  last_success_at timestamptz,
  last_error_at timestamptz,
  error_count integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.ai_provider_health(provider, status)
values ('cloudflare','unknown'), ('groq','unknown')
on conflict (provider) do nothing;

create table if not exists public.ai_engine_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info'
    check (level in ('info','warning','error')),
  category text not null,
  provider text,
  message text not null,
  meta jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_engine_logs_created_idx
  on public.ai_engine_logs(created_at desc);
create index if not exists ai_engine_logs_category_created_idx
  on public.ai_engine_logs(category, created_at desc);
create index if not exists ai_engine_logs_provider_created_idx
  on public.ai_engine_logs(provider, created_at desc);

-- 서비스 역할만 서버에서 사용. 브라우저 일반 사용자는 직접 읽거나 쓰지 않음.
alter table public.ai_provider_health enable row level security;
alter table public.ai_engine_logs enable row level security;

-- 3분 이상 processing에 멈춘 턴을 다음 서버 tick에서 복구할 수 있게 정리용 함수 제공.
create or replace function public.recover_stale_ai_turns()
returns integer
language plpgsql
security definer
set search_path='public'
as $$
declare
  v_count integer := 0;
begin
  update public.ai_turn_queue
  set status='queued',
      scheduled_at=now(),
      processed_at=null
  where status='processing'
    and scheduled_at < now() - interval '3 minutes';

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.recover_stale_ai_turns() from public, anon, authenticated;
grant execute on function public.recover_stale_ai_turns() to service_role;

commit;

-- ============================================================
-- 확인용
-- ============================================================
select provider, status, paused_until, last_error_code, last_success_at, error_count
from public.ai_provider_health
order by provider;

select count(*) as engine_log_rows
from public.ai_engine_logs;
